# Week 4

In [149]:
import pandas as pd
fields_list = pd.read_csv("W3_list_enriched.csv")
fields_list
fields_sold = pd.read_csv("W3_sold_enriched.csv")
fields_sold

/var/folders/gn/t0769g993173xwvtkqwcs0z80000gn/T/ipykernel_71196/2144162887.py:4: DtypeWarning: Columns (0,1,51,63,64,65,67,68) have mixed types. Specify dtype option on import or set low_memory=False.
  fields_sold = pd.read_csv("W3_sold_enriched.csv")

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,AssociationFee,LotSizeSquareFeet,OriginatingSystemName,OriginatingSystemSubName,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled,year_month,rate_30yr_fixed
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,False,499000.0,551985747,jwachter@cbnorcal.com,2024-01-26,240000.0,...,6472.0,NaN,CRMLS,CRMLS_MLSL,NaN,NaN,NaN,NaN,2024-01,6.6425
1,SanDiego,SanDiego,NaN,False,False,759900.0,522107581,mdarwich12@gmail.com,2024-01-05,815000.0,...,NaN,NaN,CRMLS,CRMLS_SAND,NaN,NaN,NaN,NaN,2024-01,6.6425
2,SanDiego,SanDiego,NaN,False,False,739900.0,510919001,mdarwich12@gmail.com,2024-01-05,810000.0,...,NaN,NaN,CRMLS,CRMLS_SAND,NaN,NaN,NaN,NaN,2024-01,6.6425
3,Mlslistings,Mlslistings,NaN,False,NaN,NaN,1079166779,davidmartz@compass.com,2024-01-30,858000.0,...,NaN,13504.0,CRMLS,CRMLS_MLSL,NaN,NaN,NaN,NaN,2024-01,6.6425
4,Southland,Southland,NaN,False,False,1890500.0,1075037759,karen.klein@theagencyre.com,2024-01-29,1890500.0,...,0.0,17873.0,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN,2024-01,6.6425
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414562,LakeCounty,LakeCounty,NaN,True,False,279000.0,1069708148,jessica.homesells@gmail.com,2026-04-01,215000.0,...,0.0,10019.0,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN,2026-04,6.3320
414563,TheInlandGateway,TheInlandGateway,"Carpet,Tile,Wood",False,False,449000.0,1067010583,brian@cohen-realty.com,2026-04-13,415000.0,...,0.0,12096.0,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN,2026-04,6.3320
414564,SanDiego,TriCounties,Vinyl,True,False,1579000.0,1063196193,info@homecoin.com,2026-04-16,1355000.0,...,0.0,859874.4,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN,2026-04,6.3320
414565,Mrmls,OrangeCounty,NaN,True,False,855000.0,1062106215,jefflachef@gmail.com,2026-04-16,820000.0,...,0.0,2733.0,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN,2026-04,6.3320
414566,Southland,PacificWest,"Carpet,Vinyl",False,False,375000.0,1052387780,elizabethoryan04@gmail.com,2026-04-24,380000.0,...,345.0,23878.0,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN,2026-04,6.3320

## Convert date fields to datetime format

In [150]:
#Convert date fields to datetime format (CloseDate, PurchaseContractDate, ListingContractDate,ContractStatusChangeDate)
datetime_columns = ["CloseDate", "PurchaseContractDate", "ListingContractDate","ContractStatusChangeDate"]
for col in datetime_columns:
    fields_sold[col] = pd.to_datetime(fields_sold[col], errors="coerce")
    fields_list[col] = pd.to_datetime(fields_list[col], errors="coerce")

print(fields_sold[datetime_columns].dtypes)
print(fields_list[datetime_columns].dtypes)

CloseDate                   datetime64[ns]
PurchaseContractDate        datetime64[ns]
ListingContractDate         datetime64[ns]
ContractStatusChangeDate    datetime64[ns]
dtype: object
CloseDate                   datetime64[ns]
PurchaseContractDate        datetime64[ns]
ListingContractDate         datetime64[ns]
ContractStatusChangeDate    datetime64[ns]
dtype: object

In [151]:
#Remove unnecessary or redundant columns: columns with all NaN value
fields_sold[['BuyerAgencyCompensation',
             'BuyerAgencyCompensationType',"OriginatingSystemName","BuyerOfficeName","PropertyType","LotSizeArea","LotSizeSquareFeet"]]

,BuyerAgencyCompensation,BuyerAgencyCompensationType,OriginatingSystemName,BuyerOfficeName,PropertyType,LotSizeArea,LotSizeSquareFeet
0,NaN,NaN,CRMLS,Bay Area Senior Services,Residential,NaN,NaN
1,NaN,NaN,CRMLS,FOSTER HAMILTON Real Estate,Residential,NaN,NaN
2,NaN,NaN,CRMLS,FOSTER HAMILTON Real Estate,Residential,NaN,NaN
3,NaN,NaN,CRMLS,NaN,Residential,13504.00,13504.0
4,NaN,NaN,CRMLS,The Agency - Studio City,Residential,17873.00,17873.0
...,...,...,...,...,...,...,...
414562,NaN,NaN,CRMLS,RE/MAX Gold Lake County,Residential,10019.00,10019.0
414563,NaN,NaN,CRMLS,ARROWHEAD PREMIER PROPERTIES,Residential,12096.00,12096.0
414564,NaN,NaN,CRMLS,Real Broker,Residential,19.74,859874.4
414565,NaN,NaN,CRMLS,NONMEMBER MRML,Residential,2733.00,2733.0
414566,NaN,NaN,CRMLS,"B.L.A. Properties & Loans, Inc",Residential,23878.00,23878.0

In [152]:
fields_list[["PropertyType.1","LotSizeArea","LotSizeSquareFeet"]]

       PropertyType.1  LotSizeArea  LotSizeSquareFeet
0         Residential      5121.00             5121.0
1         Residential      6501.00             6501.0
2         Residential          NaN                NaN
3         Residential     11144.00            11144.0
4         Residential   4054129.00          4054129.0
...               ...          ...                ...
512660    Residential     24226.00            24226.0
512661    Residential          NaN                NaN
512662    Residential        19.09           831560.4
512663    Residential     14810.00            14810.0
512664    Residential         2.09            91040.4

[512665 rows x 3 columns]

In [153]:
#drop null data for'BuyerAgencyCompensation','BuyerAgencyCompensationType" and redudent data for propertytype and "OriginatingSystemName"
Columns_drop_sold = ['BuyerAgencyCompensation','BuyerAgencyCompensationType',"OriginatingSystemName","PropertyType"]
Columns_drop_list = ["PropertyType.1"]

In [154]:
fields_list = pd.read_csv("W3_list_enriched.csv")
fields_list
fields_sold = pd.read_csv("W3_sold_enriched.csv")
fields_sold

/var/folders/gn/t0769g993173xwvtkqwcs0z80000gn/T/ipykernel_71196/230661549.py:3: DtypeWarning: Columns (0,1,51,63,64,65,67,68) have mixed types. Specify dtype option on import or set low_memory=False.
  fields_sold = pd.read_csv("W3_sold_enriched.csv")

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,AssociationFee,LotSizeSquareFeet,OriginatingSystemName,OriginatingSystemSubName,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled,year_month,rate_30yr_fixed
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,False,499000.0,551985747,jwachter@cbnorcal.com,2024-01-26,240000.0,...,6472.0,NaN,CRMLS,CRMLS_MLSL,NaN,NaN,NaN,NaN,2024-01,6.6425
1,SanDiego,SanDiego,NaN,False,False,759900.0,522107581,mdarwich12@gmail.com,2024-01-05,815000.0,...,NaN,NaN,CRMLS,CRMLS_SAND,NaN,NaN,NaN,NaN,2024-01,6.6425
2,SanDiego,SanDiego,NaN,False,False,739900.0,510919001,mdarwich12@gmail.com,2024-01-05,810000.0,...,NaN,NaN,CRMLS,CRMLS_SAND,NaN,NaN,NaN,NaN,2024-01,6.6425
3,Mlslistings,Mlslistings,NaN,False,NaN,NaN,1079166779,davidmartz@compass.com,2024-01-30,858000.0,...,NaN,13504.0,CRMLS,CRMLS_MLSL,NaN,NaN,NaN,NaN,2024-01,6.6425
4,Southland,Southland,NaN,False,False,1890500.0,1075037759,karen.klein@theagencyre.com,2024-01-29,1890500.0,...,0.0,17873.0,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN,2024-01,6.6425
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414562,LakeCounty,LakeCounty,NaN,True,False,279000.0,1069708148,jessica.homesells@gmail.com,2026-04-01,215000.0,...,0.0,10019.0,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN,2026-04,6.3320
414563,TheInlandGateway,TheInlandGateway,"Carpet,Tile,Wood",False,False,449000.0,1067010583,brian@cohen-realty.com,2026-04-13,415000.0,...,0.0,12096.0,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN,2026-04,6.3320
414564,SanDiego,TriCounties,Vinyl,True,False,1579000.0,1063196193,info@homecoin.com,2026-04-16,1355000.0,...,0.0,859874.4,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN,2026-04,6.3320
414565,Mrmls,OrangeCounty,NaN,True,False,855000.0,1062106215,jefflachef@gmail.com,2026-04-16,820000.0,...,0.0,2733.0,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN,2026-04,6.3320
414566,Southland,PacificWest,"Carpet,Vinyl",False,False,375000.0,1052387780,elizabethoryan04@gmail.com,2026-04-24,380000.0,...,345.0,23878.0,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN,2026-04,6.3320

## Drop redundant and unnecessary data

In [155]:
#drop redudent and unnessary data
Columns_drop_sold = [
    'BuyerAgencyCompensation',
    'BuyerAgencyCompensationType',
    'OriginatingSystemName',
    'PropertyType'
]
fields_sold.columns
fields_sold.drop(columns=Columns_drop_sold, inplace=True)
fields_sold

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,OriginatingSystemSubName,latfilled,lonfilled,year_month,rate_30yr_fixed
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,False,499000.0,551985747,jwachter@cbnorcal.com,2024-01-26,240000.0,...,1.0,Other,94401,6472.0,NaN,CRMLS_MLSL,NaN,NaN,2024-01,6.6425
1,SanDiego,SanDiego,NaN,False,False,759900.0,522107581,mdarwich12@gmail.com,2024-01-05,815000.0,...,2.0,NaN,91950,NaN,NaN,CRMLS_SAND,NaN,NaN,2024-01,6.6425
2,SanDiego,SanDiego,NaN,False,False,739900.0,510919001,mdarwich12@gmail.com,2024-01-05,810000.0,...,2.0,NaN,91950,NaN,NaN,CRMLS_SAND,NaN,NaN,2024-01,6.6425
3,Mlslistings,Mlslistings,NaN,False,NaN,NaN,1079166779,davidmartz@compass.com,2024-01-30,858000.0,...,2.0,Palm Springs Unified,92262,NaN,13504.0,CRMLS_MLSL,NaN,NaN,2024-01,6.6425
4,Southland,Southland,NaN,False,False,1890500.0,1075037759,karen.klein@theagencyre.com,2024-01-29,1890500.0,...,2.0,Los Angeles Unified,91356,0.0,17873.0,CRMLS_CRM,NaN,NaN,2024-01,6.6425
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414562,LakeCounty,LakeCounty,NaN,True,False,279000.0,1069708148,jessica.homesells@gmail.com,2026-04-01,215000.0,...,0.0,Konocti Unified,95424,0.0,10019.0,CRMLS_CRM,NaN,NaN,2026-04,6.3320
414563,TheInlandGateway,TheInlandGateway,"Carpet,Tile,Wood",False,False,449000.0,1067010583,brian@cohen-realty.com,2026-04-13,415000.0,...,0.0,Rim of the World,92322,0.0,12096.0,CRMLS_CRM,NaN,NaN,2026-04,6.3320
414564,SanDiego,TriCounties,Vinyl,True,False,1579000.0,1063196193,info@homecoin.com,2026-04-16,1355000.0,...,0.0,Sanger Unified,93619,0.0,859874.4,CRMLS_CRM,NaN,NaN,2026-04,6.3320
414565,Mrmls,OrangeCounty,NaN,True,False,855000.0,1062106215,jefflachef@gmail.com,2026-04-16,820000.0,...,2.0,Capistrano Unified,92629,0.0,2733.0,CRMLS_CRM,NaN,NaN,2026-04,6.3320
414566,Southland,PacificWest,"Carpet,Vinyl",False,False,375000.0,1052387780,elizabethoryan04@gmail.com,2026-04-24,380000.0,...,2.0,Inglewood Unified,90302,345.0,23878.0,CRMLS_CRM,NaN,NaN,2026-04,6.3320

In [156]:
fields_list.drop(columns=Columns_drop_list, inplace=True)
fields_list

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,UnparsedAddress.1,year_month,rate_30yr_fixed
0,3550000.0,1075011892,jasmineguo@firstteam.com,NaN,NaN,Meng,Guo,33.688369,-117.700659,100 Princess Pine,...,False,2.0,Irvine Unified,92618,NaN,295.0,5121.0,100 Princess Pine,2024-03,6.820
1,1599000.0,1075010394,EK@ITZSOLD.COM,NaN,NaN,Edward,Kaminsky,33.886763,-118.371293,2217 Warfield Avenue,...,False,0.0,Redondo Unified,90278,NaN,0.0,6501.0,2217 Warfield Avenue,2024-03,6.820
2,724999.0,1075001993,greg@sandiegodreamteam.com,NaN,NaN,Greg,Hill,32.777982,-117.041565,7200 Melody Lane 6,...,NaN,1.0,La Mesa-Spring Valley,91942,NaN,410.0,NaN,7200 Melody Lane 6,2024-03,6.820
3,825000.0,1075001860,mikeaon@cox.net,2024-05-08,810000.0,Mike,Aon,32.713028,-117.095232,740 Cotton Street,...,False,0.0,San Diego Unified,92102,Coldwell Banker Royal Realty,0.0,11144.0,740 Cotton Street,2024-03,6.820
4,650000.0,1075001376,clint@beckyjohns.com,NaN,NaN,Clint,Johns,40.253106,-122.481338,15015 State Highway 36 W,...,False,2.0,Red Bluff Joint Union,96080,NaN,0.0,4054129.0,15015 State Highway 36 W,2024-03,6.820
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512660,2595000.0,1153444674,denny@dennykagasoff.com,NaN,NaN,Denny,Kagasoff,34.129724,-118.394741,12004 Briarvale Lane,...,False,NaN,NaN,91604,NaN,NaN,24226.0,12004 Briarvale Lane,2026-04,6.332
512661,7285000.0,1152609167,ann@brizolisjanzen.com,NaN,NaN,K. Ann,Brizolis,32.980315,-117.198367,14480 Bellvista Dr,...,False,3.0,NaN,92067,NaN,735.0,NaN,14480 Bellvista Dr,2026-04,6.332
512662,396000.0,1151471220,jason@venture-pacific.net,NaN,NaN,Jason,Lipovsky,33.002752,-116.782659,15755 Davis Cup Lane,...,NaN,0.0,Ramona Unified,92065,NaN,596.0,831560.4,15755 Davis Cup Lane,2026-04,6.332
512663,985000.0,1149517845,aisaethan@icloud.com,NaN,NaN,Aisa,Tu,33.645255,-117.358172,33115 Evergreen Sreet,...,NaN,3.0,Lake Elsinore Unified,92530,NaN,0.0,14810.0,33115 Evergreen Sreet,2026-04,6.332
512664,450000.0,1147219386,nathaly@shoppingsdhouses.com,NaN,NaN,Nathaly,Vera,32.746368,-116.984283,9860 Dale Avenue D2,...,NaN,0.0,Other,91977,NaN,510.0,91040.4,9860 Dale Avenue D2,2026-04,6.332

In [157]:
#Handle missing values appropriately
missing_sold = (fields_sold.isna().sum()).sort_values(ascending=False)
missing_list = (fields_list.isna().sum()).sort_values(ascending=False)
print(missing_sold)
print(missing_list)

ElementarySchool            359403
MiddleOrJuniorSchool        359021
OriginatingSystemSubName    358855
lonfilled                   350683
latfilled                   350683
                             ...
MlsStatus                        0
ListingId                        0
ListOfficeName                   0
StateOrProvince                  0
rate_30yr_fixed                  0
Length: 67, dtype: int64
MiddleOrJuniorSchool    451597
ElementarySchool        451524
HighSchool              432410
ClosePrice              400485
CoListAgentFirstName    398501
                         ...
DaysOnMarket.1               0
ListPrice.1                  0
ListingId                    0
ListingContractDate          0
rate_30yr_fixed              0
Length: 70, dtype: int64

In [158]:
#fill numeric NaN with medium to ensure the dataset is filled
numeric_cols_sold = fields_sold.select_dtypes(include='number').columns
fields_sold[numeric_cols_sold] = fields_sold[numeric_cols_sold].fillna(
    fields_sold[numeric_cols_sold].median()
)

numeric_cols_list = fields_list.select_dtypes(include='number').columns
fields_list[numeric_cols_list] = fields_list[numeric_cols_list].fillna(
    fields_list[numeric_cols_list].median()
)

In [159]:
missing_sold = (fields_sold.isna().sum()).sort_values(ascending=False)
print(missing_sold)

ElementarySchool            359403
MiddleOrJuniorSchool        359021
OriginatingSystemSubName    358855
lonfilled                   350683
latfilled                   350683
                             ...
YearBuilt                        0
StreetNumberNumeric              0
DaysOnMarket                     0
BathroomsTotalInteger            0
rate_30yr_fixed                  0
Length: 67, dtype: int64

In [160]:
#Ensure numeric fields are properly typed
numeric_fields = ["ClosePrice", "ListPrice", "OriginalListPrice", "LivingArea","LotSizeAcres", "BedroomsTotal", "BathroomsTotalInteger", "DaysOnMarket", "YearBuilt"]
for col in numeric_fields:
    fields_sold[col] = pd.to_numeric(fields_sold[col], errors='coerce')
print(fields_sold[numeric_fields].dtypes)

ClosePrice               float64
ListPrice                float64
OriginalListPrice        float64
LivingArea               float64
LotSizeAcres             float64
BedroomsTotal            float64
BathroomsTotalInteger    float64
DaysOnMarket               int64
YearBuilt                float64
dtype: object

## Flag invalid numeric values

In [ ]:
#flag invalid numeric values for sold: 
# ClosePrice <= 0, LivingArea <= 0, DaysOnMarket < 0,negative Bedrooms or Bathrooms
fields_sold["InvalidValues"]= (
    (fields_sold["ClosePrice"] <= 0) |
    (fields_sold["LivingArea"] <= 0) |
    (fields_sold["DaysOnMarket"] < 0) |
    (fields_sold["BedroomsTotal"] < 0) |
    (fields_sold["BathroomsTotalInteger"] < 0)
)

fields_sold["InvalidValues"]
fields_sold["InvalidValues"].value_counts()

InvalidValues
False    414364
True        203
Name: count, dtype: int64

In [162]:
#finding the clomums that are invalid
fields_sold[fields_sold["InvalidValues"] == True]

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,OriginatingSystemSubName,latfilled,lonfilled,year_month,rate_30yr_fixed,InvalidValues
6,CoastalMendocino,CoastalMendocino,Tile,True,False,1950000.0,1063453216,kira@mendosir.com,2024-01-22,1950000.0,...,NaN,95437,96.0,74487.6,CRMLS_CRF,NaN,NaN,2024-01,6.6425,True
7708,Malibu,Malibu,Wood,True,NaN,8295000.0,1046380894,benjamin@illulianrealty.com,2024-01-22,8000000.0,...,NaN,90210,96.0,19987.0,CRMLS_CL,NaN,NaN,2024-01,6.6425,True
11214,NaN,NaN,"Carpet,Tile",True,True,899000.0,1062122119,thewalkers@bdhomes.com,2024-02-26,899000.0,...,NaN,92210,650.0,4792.0,NaN,NaN,NaN,2024-02,6.7760,True
11381,NaN,NaN,NaN,False,False,372000.0,1061302766,hello@yourdesertlife.org,2024-02-23,372000.0,...,NaN,92507,96.0,10454.0,NaN,NaN,NaN,2024-02,6.7760,True
18698,NaN,NaN,NaN,False,False,699900.0,1052574395,kristyglinski@gmail.com,2024-02-05,700000.0,...,NaN,93036,96.0,6190.0,NaN,NaN,NaN,2024-02,6.7760,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
400146,Oakland,Oakland,Wood,NaN,False,1495000.0,1155594867,Heidi@HomesByHeidi.com,2026-04-10,1825000.0,...,NaN,94611,96.0,4380.0,CRMLS_BMLS,NaN,NaN,2026-04,6.3320,True
404731,Mrmls,SanDiego,"Stone,Tile,Wood",False,False,379000.0,1154279551,niroaloni@gmail.com,2026-04-24,385000.0,...,NaN,92587,96.0,7239.0,CRMLS_SAND,NaN,NaN,2026-04,6.3320,True
412685,InlandValleys,InlandValleys,"Carpet,Tile",True,False,530000.0,1146833920,team@providencerealty.net,2026-04-28,530000.0,...,San Bernardino City Unified,92404,0.0,12000.0,CRMLS_CRM,NaN,NaN,2026-04,6.3320,True
413210,CaliforniaDesert,CaliforniaDesert,NaN,True,False,185000.0,1144953066,jimlnewcomb@aol.com,2026-04-17,165000.0,...,Rim of the World,92352,1150.0,0.0,CRMLS_CDAR,NaN,NaN,2026-04,6.3320,True
414491,Malibu,Malibu,Wood,True,True,2450000.0,1108520884,brian@luxurymalibuproperty.com,2026-04-01,2075000.0,...,Santa Monica-Malibu Unified,90265,96.0,262281.0,CRMLS_CL,NaN,NaN,2026-04,6.3320,True

In [163]:
#do the same process for list: 
fields_list["InvalidValues"]= (
    (fields_list["ClosePrice"] <= 0) |
    (fields_list["LivingArea"] <= 0) |
    (fields_list["DaysOnMarket"] < 0) |
    (fields_list["BedroomsTotal"] < 0) |
    (fields_list["BathroomsTotalInteger"] < 0)
)

fields_list["InvalidValues"]
fields_list["InvalidValues"].value_counts()

InvalidValues
False    512308
True        357
Name: count, dtype: int64

In [164]:
fields_list[fields_list["InvalidValues"] == True]

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,UnparsedAddress.1,year_month,rate_30yr_fixed,InvalidValues
3047,759880.0,1064982371,BrokerRyan26@gmail.com,NaN,857500.0,RYAN,JOHNSON,34.188599,-118.947732,728 Malat Drive,...,2.0,Conejo Valley Unified,91320,NaN,0.0,8056.0,728 Malat Drive,2024-03,6.820,True
3268,330000.0,1064943439,alejandroateam@gmail.com,NaN,857500.0,Alejandro,Perez-Munoz,33.731741,-116.354205,43376 Cook Street 216,...,0.0,NaN,92211,NaN,360.0,1008.0,43376 Cook Street 216,2024-03,6.820,True
3898,5495000.0,1064918337,elizabeth@elizabethdonovanrealty.com,NaN,857500.0,Elizabeth,Donovan,33.754237,-118.351796,7 Cinchring Road,...,2.0,NaN,90274,NaN,0.0,44272.0,7 Cinchring Road,2024-03,6.820,True
4788,4950000.0,1064842198,drew@drewfenton.com,NaN,857500.0,Drew,Fenton,34.054218,-118.484005,204 S Canyon View Drive,...,2.0,NaN,90049,NaN,125.0,8068.0,204 S Canyon View Drive,2024-03,6.820,True
9626,880000.0,1063458939,astephan@livsothebysrealty.com,2024-03-15,880000.0,Anna,Stephan,34.274754,-119.183685,8214 Platinum Street,...,2.0,NaN,93004,LIV Sotheby's International Realty,18.0,3340.0,8214 Platinum Street,2024-03,6.820,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
504766,129900.0,1157241154,pete@pls-realty.com,NaN,857500.0,Peter,Sutton,33.704214,-116.264162,80394 Ave 48 331,...,0.0,NaN,92201,NaN,670.0,2178.0,80394 Ave 48 331,2026-04,6.332,True
506166,29500000.0,1157083610,cristal@montecito-estate.com,NaN,857500.0,Cristal,Clarke,34.441939,-119.648690,771 Garden Lane,...,2.0,NaN,93108,NaN,125.0,0.0,771 Garden Lane,2026-04,6.332,True
508579,3750000.0,1156895233,martyhalfon90210@gmail.com,NaN,857500.0,Martin,Halfon,34.094435,-118.417750,1309 Laurel Way,...,2.0,NaN,90210,NaN,125.0,21156.0,1309 Laurel Way,2026-04,6.332,True
510353,1899000.0,1156773955,Derek@TheEstatesGroup.org,NaN,857500.0,Derek,Saelee,40.878096,-121.925024,20441 Cove Road,...,2.0,NaN,96065,NaN,125.0,11508552.0,20441 Cove Road,2026-04,6.332,True
510785,6250000.0,1156726419,alex.purewal@theagencyre.com,NaN,857500.0,Alexander,Purewal,34.015487,-118.801789,28926 Boniface Drive,...,2.0,NaN,90265,NaN,125.0,73288.0,28926 Boniface Drive,2026-04,6.332,True

# Data consistency checks for sold and list

In [ ]:
#data consistency checks for sold
fields_sold["listing_after_close_flag"] = fields_sold["ListingContractDate"] > fields_sold["CloseDate"]
fields_sold["purchase_after_close_flag"] = fields_sold["PurchaseContractDate"] > fields_sold["CloseDate"]
fields_sold["negative_timeline_flag"] = ((fields_sold["PurchaseContractDate"] < fields_sold["ListingContractDate"]) |
    (fields_sold["CloseDate"] < fields_sold["PurchaseContractDate"]))
fields_sold

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,LotSizeSquareFeet,OriginatingSystemSubName,latfilled,lonfilled,year_month,rate_30yr_fixed,InvalidValues,listing_after_close_flag,purchase_after_close_flag,negative_timeline_flag
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,False,499000.0,551985747,jwachter@cbnorcal.com,2024-01-26,240000.0,...,7239.0,CRMLS_MLSL,NaN,NaN,2024-01,6.6425,False,False,False,False
1,SanDiego,SanDiego,NaN,False,False,759900.0,522107581,mdarwich12@gmail.com,2024-01-05,815000.0,...,7239.0,CRMLS_SAND,NaN,NaN,2024-01,6.6425,False,False,False,False
2,SanDiego,SanDiego,NaN,False,False,739900.0,510919001,mdarwich12@gmail.com,2024-01-05,810000.0,...,7239.0,CRMLS_SAND,NaN,NaN,2024-01,6.6425,False,False,False,False
3,Mlslistings,Mlslistings,NaN,False,NaN,825000.0,1079166779,davidmartz@compass.com,2024-01-30,858000.0,...,13504.0,CRMLS_MLSL,NaN,NaN,2024-01,6.6425,False,False,True,True
4,Southland,Southland,NaN,False,False,1890500.0,1075037759,karen.klein@theagencyre.com,2024-01-29,1890500.0,...,17873.0,CRMLS_CRM,NaN,NaN,2024-01,6.6425,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414562,LakeCounty,LakeCounty,NaN,True,False,279000.0,1069708148,jessica.homesells@gmail.com,2026-04-01,215000.0,...,10019.0,CRMLS_CRM,NaN,NaN,2026-04,6.3320,False,False,False,False
414563,TheInlandGateway,TheInlandGateway,"Carpet,Tile,Wood",False,False,449000.0,1067010583,brian@cohen-realty.com,2026-04-13,415000.0,...,12096.0,CRMLS_CRM,NaN,NaN,2026-04,6.3320,False,False,False,False
414564,SanDiego,TriCounties,Vinyl,True,False,1579000.0,1063196193,info@homecoin.com,2026-04-16,1355000.0,...,859874.4,CRMLS_CRM,NaN,NaN,2026-04,6.3320,False,False,False,False
414565,Mrmls,OrangeCounty,NaN,True,False,855000.0,1062106215,jefflachef@gmail.com,2026-04-16,820000.0,...,2733.0,CRMLS_CRM,NaN,NaN,2026-04,6.3320,False,False,False,False
414566,Southland,PacificWest,"Carpet,Vinyl",False,False,375000.0,1052387780,elizabethoryan04@gmail.com,2026-04-24,380000.0,...,23878.0,CRMLS_CRM,NaN,NaN,2026-04,6.3320,False,False,False,False

In [169]:
fields_sold["purchase_after_close_flag"].value_counts()

purchase_after_close_flag
False    414317
True        250
Name: count, dtype: int64

In [172]:
#data consistency checks for list
fields_list["listing_after_close_flag"] = fields_list["ListingContractDate"] > fields_list["CloseDate"]
fields_list["purchase_after_close_flag"] = fields_list["PurchaseContractDate"] > fields_list["CloseDate"]
fields_list["negative_timeline_flag"] = ((fields_list["PurchaseContractDate"] < fields_list["ListingContractDate"]) |
    (fields_list["CloseDate"] < fields_list["PurchaseContractDate"]))
fields_list

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,UnparsedAddress.1,year_month,rate_30yr_fixed,InvalidValues,listing_after_close_flag,purchase_after_close_flag,negative_timeline_flag
0,3550000.0,1075011892,jasmineguo@firstteam.com,NaN,857500.0,Meng,Guo,33.688369,-117.700659,100 Princess Pine,...,NaN,295.0,5121.0,100 Princess Pine,2024-03,6.820,False,False,False,False
1,1599000.0,1075010394,EK@ITZSOLD.COM,NaN,857500.0,Edward,Kaminsky,33.886763,-118.371293,2217 Warfield Avenue,...,NaN,0.0,6501.0,2217 Warfield Avenue,2024-03,6.820,False,False,False,False
2,724999.0,1075001993,greg@sandiegodreamteam.com,NaN,857500.0,Greg,Hill,32.777982,-117.041565,7200 Melody Lane 6,...,NaN,410.0,7405.0,7200 Melody Lane 6,2024-03,6.820,False,False,False,False
3,825000.0,1075001860,mikeaon@cox.net,2024-05-08,810000.0,Mike,Aon,32.713028,-117.095232,740 Cotton Street,...,Coldwell Banker Royal Realty,0.0,11144.0,740 Cotton Street,2024-03,6.820,False,False,False,False
4,650000.0,1075001376,clint@beckyjohns.com,NaN,857500.0,Clint,Johns,40.253106,-122.481338,15015 State Highway 36 W,...,NaN,0.0,4054129.0,15015 State Highway 36 W,2024-03,6.820,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512660,2595000.0,1153444674,denny@dennykagasoff.com,NaN,857500.0,Denny,Kagasoff,34.129724,-118.394741,12004 Briarvale Lane,...,NaN,125.0,24226.0,12004 Briarvale Lane,2026-04,6.332,False,False,False,False
512661,7285000.0,1152609167,ann@brizolisjanzen.com,NaN,857500.0,K. Ann,Brizolis,32.980315,-117.198367,14480 Bellvista Dr,...,NaN,735.0,7405.0,14480 Bellvista Dr,2026-04,6.332,False,False,False,False
512662,396000.0,1151471220,jason@venture-pacific.net,NaN,857500.0,Jason,Lipovsky,33.002752,-116.782659,15755 Davis Cup Lane,...,NaN,596.0,831560.4,15755 Davis Cup Lane,2026-04,6.332,False,False,False,False
512663,985000.0,1149517845,aisaethan@icloud.com,NaN,857500.0,Aisa,Tu,33.645255,-117.358172,33115 Evergreen Sreet,...,NaN,0.0,14810.0,33115 Evergreen Sreet,2026-04,6.332,False,False,False,False
512664,450000.0,1147219386,nathaly@shoppingsdhouses.com,NaN,857500.0,Nathaly,Vera,32.746368,-116.984283,9860 Dale Avenue D2,...,NaN,510.0,91040.4,9860 Dale Avenue D2,2026-04,6.332,False,False,False,False

## Geographic Data Checks

In [177]:
#Flag records with missing coordinates (Latitude or Longitude is null)
fields_sold["missing_sold"] = fields_sold["Latitude"].isna() | fields_sold["Longitude"].isna()
fields_sold
fields_sold["missing_sold"].value_counts()

missing_sold
False    414567
Name: count, dtype: int64

Result: There is no null or missing data for longitude or latitude

In [ ]:
#Flag Latitude = 0 or Longitude = 0 (sentinel null values)
fields_sold["sentinel_null_values"] = ((fields_sold["Latitude"] == 0) | (fields_sold["Longitude"] == 0))
fields_sold

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,latfilled,lonfilled,year_month,rate_30yr_fixed,InvalidValues,listing_after_close_flag,purchase_after_close_flag,negative_timeline_flag,missing_sold,sentinel_null_values
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,False,499000.0,551985747,jwachter@cbnorcal.com,2024-01-26,240000.0,...,NaN,NaN,2024-01,6.6425,False,False,False,False,False,False
1,SanDiego,SanDiego,NaN,False,False,759900.0,522107581,mdarwich12@gmail.com,2024-01-05,815000.0,...,NaN,NaN,2024-01,6.6425,False,False,False,False,False,False
2,SanDiego,SanDiego,NaN,False,False,739900.0,510919001,mdarwich12@gmail.com,2024-01-05,810000.0,...,NaN,NaN,2024-01,6.6425,False,False,False,False,False,False
3,Mlslistings,Mlslistings,NaN,False,NaN,825000.0,1079166779,davidmartz@compass.com,2024-01-30,858000.0,...,NaN,NaN,2024-01,6.6425,False,False,True,True,False,False
4,Southland,Southland,NaN,False,False,1890500.0,1075037759,karen.klein@theagencyre.com,2024-01-29,1890500.0,...,NaN,NaN,2024-01,6.6425,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414562,LakeCounty,LakeCounty,NaN,True,False,279000.0,1069708148,jessica.homesells@gmail.com,2026-04-01,215000.0,...,NaN,NaN,2026-04,6.3320,False,False,False,False,False,False
414563,TheInlandGateway,TheInlandGateway,"Carpet,Tile,Wood",False,False,449000.0,1067010583,brian@cohen-realty.com,2026-04-13,415000.0,...,NaN,NaN,2026-04,6.3320,False,False,False,False,False,False
414564,SanDiego,TriCounties,Vinyl,True,False,1579000.0,1063196193,info@homecoin.com,2026-04-16,1355000.0,...,NaN,NaN,2026-04,6.3320,False,False,False,False,False,False
414565,Mrmls,OrangeCounty,NaN,True,False,855000.0,1062106215,jefflachef@gmail.com,2026-04-16,820000.0,...,NaN,NaN,2026-04,6.3320,False,False,False,False,False,False
414566,Southland,PacificWest,"Carpet,Vinyl",False,False,375000.0,1052387780,elizabethoryan04@gmail.com,2026-04-24,380000.0,...,NaN,NaN,2026-04,6.3320,False,False,False,False,False,False

In [188]:
fields_sold["positive_logitude_error"] = (fields_sold["Longitude"] > 0 )
fields_sold
fields_sold["positive_logitude_error"].value_counts()

positive_logitude_error
False    414538
True         29
Name: count, dtype: int64

There are 29 positive longitude error

In [195]:
# Flag out-of-state or implausible coordinates
fields_sold["Invalidcoordinates"] = (
    (fields_sold["Latitude"] < -90) |
    (fields_sold["Latitude"] > 90) |
    (fields_sold["Longitude"] < -180) |
    (fields_sold["Longitude"] > 180) | (fields_sold["Latitude"] < 32.5) |
    (fields_sold["Latitude"] > 42.0) |
    (fields_sold["Longitude"] < -124.5) |
    (fields_sold["Longitude"] > -114.0))
fields_sold["Invalidcoordinates"].value_counts()

Invalidcoordinates
False    414479
True         88
Name: count, dtype: int64

In [196]:
fields_sold[fields_sold["Invalidcoordinates"] == True]

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,InvalidValues,listing_after_close_flag,purchase_after_close_flag,negative_timeline_flag,missing_sold,sentinel_null_values,positive_logitude_error,Out_of_states,Implausible,Invalidcoordinates
9721,PacificWest,PacificWest,NaN,False,False,810000.0,1044978778,miguelgrijalva@socalrealtygrp.co,2024-01-23,735000.0,...,False,False,False,False,False,False,True,True,False,True
23086,NaN,NaN,NaN,False,False,798000.0,1045537743,dancrobles1@hotmail.com,2024-02-02,730000.0,...,False,False,False,False,False,False,True,True,False,True
37275,NaN,NaN,NaN,True,False,709655.0,1050732402,wcziccardi@kbhome.com,2024-03-04,710080.0,...,False,False,False,False,False,False,True,True,False,True
39831,NaN,NaN,Laminate,True,False,795000.0,1038636035,rick@commutercars.com,2024-03-05,750000.0,...,False,False,False,False,False,False,False,True,False,True
53809,NaN,NaN,NaN,False,False,218000.0,1058731536,cynthia.jauregui@exprealty.com,2024-04-05,196000.0,...,False,False,False,False,False,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397807,Mlslistings,Mlslistings,"Carpet,Tile",False,NaN,788900.0,1111813191,newhomesbayarea@tripointehomes.com,2026-03-19,735000.0,...,False,False,False,False,False,True,False,True,False,True
402033,Malibu,InlandValleys,NaN,False,False,389000.0,1155114006,bryan@inlandrealtyempire.com,2026-04-09,415000.0,...,False,False,False,False,False,False,True,True,False,True
403255,HighDesert,HighDesert,"Carpet,Tile",True,False,320000.0,1154773896,Rhonda@cbhomesource.com,2026-04-23,315000.0,...,False,False,False,False,False,False,True,True,False,True
406026,Mrmls,Madera,NaN,False,False,298000.0,1153563387,nittacasa@yahoo.com,2026-04-24,291500.0,...,False,False,False,False,False,True,False,True,False,True
414210,Mlslistings,Mlslistings,"Carpet,Tile",True,NaN,699900.0,1119199475,newhomesbayarea@tripointehomes.com,2026-04-16,689000.0,...,False,False,False,False,False,True,False,True,False,True

Based on the result, there are 88 data that have invalid coordinates. The coordinate for california is 32.5-42 for latitude and -124.5 to -114.0 for longitute, anything outside of the range is considered outside of state. Additionally, a laitiude must be between -90 and 90 and longitude must be between -180 to 180. Based on there data there are some out of state and impossible coordinates.

In [197]:
fields_sold.to_csv("W4-5_sold_data.csv", index=False)
fields_list.to_csv("W4-5_list_data.csv", index=False)